version: 1.0.{build}
branches:
  only:
  - develop
  - master
image: Visual Studio 2017
configuration: Release
init:
- cmd: ''
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  NEventStore.MsSql: Server=localhost\SQL2014;Database=NEventStore;User Id=sa;Password=Password12!;
  NEventStore.MySql: Server=localhost;Database=NEventStore;Uid=root;Pwd=Password12!;AutoEnlist=false;
  NEventStore.PostgreSql: Server=localhost;Database=NEventStore;Uid=postgres;Pwd=Password12!;Enlist=false;
services:
- mssql2014
- mysql
- postgresql
install:
- cmd: >-
    choco install gitversion.portable -pre -y

    git submodule update --init --recursive
before_build:
- ps: >-
    # Display .NET Core version

    dotnet --version

    # Display minimal restore text

    dotnet restore ./src/NEventStore.Persistence.Sql.Core.sln --verbosity m

    gitversion /l console /output buildserver /updateAssemblyInfo
build:
  project: src\NEventStore.Persistence.Sql.Core.sln
  verbosity: minimal
after_build:
- cmd: >-
    REM dotnet pack ./src/NEventStore.Persistence.Sql/NEventStore.Persistence.Sql.Core.csproj -c %CONFIGURATION% --no-build -o artifacts /p:PackageVersion=%GitVersion_NuGetVersion%

    nuget pack ./src/.nuget/NEventStore.Persistence.Sql.nuspec -properties "version=%GitVersion_NuGetVersion%;configuration=%CONFIGURATION%" -OutputDirectory artifacts
test:
  assemblies:
    except:
    - NEventStore.Persistence.AcceptanceTests.dll
artifacts:
- path: '**\artifacts\**\*.*'